videoplayer_project/acount/urls.py
from django.urls import path

from . import views


app_name = 'acount'
urlpatterns = [
    path("login/", views.login, name="login"), 
    path("signup/logincheck/", views.logincheck, name="logincheck"), 
    path("signup/", views.signup, name="signup"), 
    path("signup/signuprecord/", views.signuprecord, name="signuprecord")
]

videoplayer_project/home/urls.py
from django.urls import path

from . import views


app_name = 'home'
urlpatterns = [
    path("", views.index, name="index"), 
    path("<int:video_id>/", views.detail, name="detail"), 
    path("<int:video_id>/post_comment/", views.post_comment, name="post_comment"), 
    path("search/", views.search, name="search"), 
]

videoplayer_project/videoplayer_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include("home.urls")), 
    path('acount/', include("acount.urls"))
]

videoplayer_project/acount/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=30)
    email_address = models.EmailField(max_length=40)
    password = models.CharField(max_length=80)
    
    def __str__(self) -> str:
        return self.username

videoplayer_project/home/models.py
from django.db import models

from acount.models import User


class Video(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    path = models.CharField(max_length=100)
    pub_date = models.DateTimeField(auto_now_add=True)
    like = models.IntegerField(default=0)
    dislike = models.IntegerField(default=0)
    
    def __str__(self) -> str:
        return self.title
    

class Comment(models.Model):
    # owner = models.ForeignKey(User, on_delete=models.CASCADE)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=700)
    pub_date = models.DateTimeField(auto_now_add=True)
    like = models.IntegerField(default=0)
    dislike = models.IntegerField(default=0)
    
    

videoplayer_project/acount/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse

from .models import User


def login(request):
    template = 'acount/login.html'
    
    return HttpResponse(render(request, template, {}))


def logincheck(request):
    pass


def signup(request):
    template = 'acount/signup.html'
    
    return HttpResponse(render(request, template, {}))


def signuprecord(request):
    un = request.POST['username']
    em = request.POST['email_address']
    pw = request.POST['password']
    
    user = User(
        username = un, 
        email_address = em, 
        password = pw
    )
    user.save()
    
    return HttpResponse(render(request, "acount/login.html", {}))

videoplayer_project/home/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.db.models import Q

from .models import Video


def index(request):
    videos_list = Video.objects.all()
    template = 'home/index.html'
    context = {
        'videos_list': videos_list
    }
    
    return HttpResponse(render(request, template, context))


def detail(request, video_id):
    video_selected = get_object_or_404(Video, id=video_id)
    videos_list = Video.objects.filter(~Q(id=video_id))
    comments_list = video_selected.comment_set.all()
    
    template = 'home/detail.html'
    context = {
        'video_selected': video_selected, 
        'videos_list': videos_list, 
        'comments_list': comments_list, 
    }
    
    return HttpResponse(render(request, template, context))


def search(request):
    video_title = request.GET['search-navbar']
    video_searched = get_object_or_404(Video, title=video_title)
    videos_list = Video.objects.filter(~Q(id=video_searched.id))
    comments_list = video_searched.comment_set.all()
    
    template = 'home/detail.html'
    context = {
        'video_selected': video_searched, 
        'videos_list': videos_list, 
        'comments_list': comments_list, 
    }
    
    return HttpResponse(render(request, template, context))


def post_comment(request, video_id):
    new_comment = request.POST['commentInput']
    vid = get_object_or_404(Video, id=video_id)
    videos_list = Video.objects.filter(~Q(id=vid.id))
    
    vid.comment_set.create(
        video = vid, 
        comment_text = new_comment
    )
    comments_list = vid.comment_set.all()
    
    template = 'home/detail.html'
    context = {
        'video_selected': vid, 
        'videos_list': videos_list, 
        'comments_list': comments_list, 
    }
    
    return HttpResponse(render(request, template, context))

videoplayer_project/acount/templates/acount/login.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/indexStyles.css' %}">
<nav>
    <div class="navbar-left">
        <ul>
            <li><a href="{% url 'home:index' %}">HOME</a></li>
            <div class="navbar-search">
                <form action="{% url 'home:search' %}">
                    {% csrf_token %}
                    <input 
                        type="text"
                        placeholder="Search videos"
                        name="search-navbar"
                        id="search-navbar"
                    >
                    <input type="submit" value="search">
                </form>
            </div>
        </ul>
    </div>
    <div class="navbar-right">
        
    </div>
</nav>

<section class="main-container">
    <form action="{% url 'acount:logincheck' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>Log in</h1></legend>

            <label for="username">Username:</label>
            <input type="text" name="username" id="username">

            <label for="password">Password:</label>
            <input type="password" name="password" id="password">
        </fieldset>
        <input type="submit" value="Submit">
    </form>

    <p>If you dont have an account yet, <a href="{% url 'acount:signup' %}">Sign up</a></p>
</section>

videoplayer_project/acount/templates/acount/signup.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/indexStyles.css' %}">
<nav>
    <div class="navbar-left">
        <ul>
            <li><a href="{% url 'home:index' %}">HOME</a></li>
            <div class="navbar-search">
                <form action="{% url 'home:search' %}">
                    {% csrf_token %}
                    <input 
                        type="text"
                        placeholder="Search videos"
                        name="search-navbar"
                        id="search-navbar"
                    >
                    <input type="submit" value="search">
                </form>
            </div>
        </ul>
    </div>
    <div class="navbar-right">
        
    </div>
</nav>

<section class="main-container">
    <form action="{% url 'acount:signuprecord' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>Sign in</h1></legend>

            <label for="username">Username:</label>
            <input type="text" name="username" id="username">

            <label for="email_address">Email:</label>
            <input type="email" name="email_address" id="email_address">

            <label for="password">Password:</label>
            <input type="password" name="password" id="password">
        </fieldset>
        <input type="submit" value="Submit">
    </form>

    <p>If you already have an account, <a href="{% url 'acount:login' %}">Log in</a></p>
</section>

videoplayer_project/home/templates/home/detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/indexStyles.css' %}">
<nav>
    <div class="navbar-left">
        <ul>
            <li><a href="{% url 'home:index' %}">HOME</a></li>
            <div class="navbar-search">
                <form action="{% url 'home:search' %}">
                    {% csrf_token %}
                    <input 
                        type="text"
                        placeholder="Search videos"
                        name="search-navbar"
                        id="search-navbar"
                    >
                    <input type="submit" value="search">
                </form>
            </div>
        </ul>
    </div>
    <div class="navbar-right">
        <ul>
            {% if acount_id %}
                <li><a href="">{{ user.name }}</a></li>
                <li><a href="">Log out</a></li>
            {% else %}
                <li><a href="{% url 'acount:login' %}">Log in</a></li>
                <li><a href="{% url 'acount:signup' %}">Sign up</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<section class="main-container">
    <div class="main-container_video">
        <div class="main-video">
            <video height="250" width="500" controls>
                <source src="{{ video_selected.path }}" type="video/mp4">
            </video>
            <h3>{{ video_selected.title }}</h3>
            <h5>{{ video_selected.pub_date }}</h2>
        </div>

        <div class="main-comments">
            <h3>Comments</h3>

            <form action="{% url 'home:post_comment' video_selected.id %}" method="post">
                {% csrf_token %}
                <input type="text" name="commentInput" id="commentInput">
                <input type="submit" value="post">
            </form>

            {% if comments_list %}
                {% for comment in comments_list %}
                    <div class="commentDetail">
                        <h6>{{ comment.pub_date }}</h6>
                        <p>{{ comment.comment_text }}</p>

                        <div>
                            <button></button>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <h3>Be the first to comment</h3>
            {% endif %}
        </div>
    </div>

    <div class="main-container_videos-list">
        {% for video in videos_list %}
            <a href="{% url 'home:detail' video.id %}">
                <div class="cards-container">
                    <video height="100" width="200">
                        <source src="{{ video.path }}" type="video/mp4">
                    </video>
                    <h5>{{ video.title }}</h5>
                </div>
            </a>
        {% endfor %}
    </div>
</section>

videoplayer_project/home/templates/home/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/indexStyles.css' %}">
<nav>
    <div class="navbar-left">
        <ul>
            <li><a href="{% url 'home:index' %}">HOME</a></li>
            <div class="navbar-search">
                <form action="{% url 'home:search' %}">
                    {% csrf_token %}
                    <input 
                        type="text"
                        placeholder="Search videos"
                        name="search-navbar"
                        id="search-navbar"
                    >
                    <input type="submit" value="search">
                </form>
            </div>
        </ul>
    </div>
    <div class="navbar-right">
        <ul>
            {% if acount_id %}
                <li><a href="">{{ user.name }}</a></li>
                <li><a href="">Log out</a></li>
            {% else %}
                <li><a href="{% url 'acount:login' %}">Log in</a></li>
                <li><a href="{% url 'acount:signup' %}">Sign up</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<section class="main-container">
    {% if videos_list %}
        {% for video in videos_list %}
            <div class="cards-container">
                <a href="{% url 'home:detail' video.id %}">
                    <div class="video-card">
                        <video height="140" width="240">
                            <source src="{{ video.path }}" type="video/mp4">
                        </video>
                        
                        <div class="video-info">
                            <div>
                                <p>{{ video.title }}</p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    {% else %}
        <h3>No videos are avaiable. :(</h3>
    {% endif %}
</section>